// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using VisionWebService.Database;

namespace VisionWebService.Migrations
{
    [DbContext(typeof(VisionServerContext))]
    [Migration("20180708212808_AddFundamentals")]
    partial class AddFundamentals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("VisionLib.Models.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArtistID");

                    b.Property<string>("Label");

                    b.HasKey("AlbumID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("VisionLib.Models.Artist", b =>
                {
                    b.Property<int>("ArtistID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ArtistID");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("VisionLib.Models.Track", b =>
                {
                    b.Property<int>("TrackID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AlbumID");

                    b.Property<int?>("ArtistID");

                    b.Property<string>("Title");

                    b.HasKey("TrackID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("VisionLib.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("HashedPassword");

                    b.Property<string>("LoginName");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VisionLib.Models.Album", b =>
                {
                    b.HasOne("VisionLib.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistID");
                });

            modelBuilder.Entity("VisionLib.Models.Track", b =>
                {
                    b.HasOne("VisionLib.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumID");

                    b.HasOne("VisionLib.Models.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistID");
                });
#pragma warning restore 612, 618
        }
    }
}
